### PR TITLE
[Card Open] - Device Screen Responsivity

### PR DESCRIPTION
**Pull request by fernandoMessias**
This commit implements responsivity in the device screen when card is open.

### CODE REVIEW

**Comment by mmagr** [comment]
@fernandoMessias please give your input on this.

Anyways, I think that between the three of us, we have a consensus to change the behavior to a link to the detailed device page, as opposed to the current expanded card, at least on non 1080p resolutions.

**Comment by fernandoMessias** [comment]
I agree that removes the expanded card in medium and smaller screen is the best idea. When i was working on this screen i thought about it. What about large screen? I think that we can leave it the way it is. I have tried to keep the same screen in all resolution but this is becoming increasingly difficult.

**Comment by mmagr** [comment]
Well I think we have a consensus then - on small- and medium-sized viewports the expanded card view should be removed, in favor of having the user being redirected to the detailed device page (in favor: 3, against 0).

As for the large viewport, I'm actually in favor of keeping the same behavior (that is, when clicking on a card the user is redirected to the device detail page). The rationale behind this is that, unless the expanded card takes on huge horizontal space, the card will almost *never show all the attributes' values*. That said, if we're to maintain the expanded card for large screens, I think we'd have to rethink what's displayed on it - perhaps just a list of attributes and their current values; perhaps just the attribute names?

What are your thoughts on this?

**Comment by fernandoMessias** [comment]
On large screens, I see no problem in displaying a list of attributes and their values. Sorry if i'm going too far at the moment, but it may be cool for the user to be able to choose the attributes he wants to see. I think that would solve part of the problem... maybe we can think about it in the future.

**Comment by mmagr** [comment]
This discussion will be implemented by #19

**Pull request closed without merging**
